<?php
  $currentURL = Mage::helper('showdetail/data')->currentURL();
  if (strlen($currentURL) == 0){
    $currentURL = 'no id';
  }
  $id = '10820963';
  $key = '95052e1b892a28c5f89f696edf39b4ec';
  $url = 'http://api.adoptapet.com/search/limited_pet_details?pet_id='. $id .'&key='. $key  .'&output=json';
  $showDetail = Mage::helper('showdetail/data')->showDetail($url);

  $arrayData = json_decode($showDetail);
?>

<style>
.showdetail-index-index {
}
.showdetail-index-index .main {
  background: #fff;
}
.showdetail-index-index .breadcrumbs {
  background: #f7f7f7;
}


.row {
  position: relative;
  clear: both;
  width: 100%;
}
.col {
  float: left;
}
.col33 {
  width: 29%;
  margin: 0 2%;
}
.col66 {
  width: 66%;
}

#petDetail {
  clear: both;
  width: 100%;
  margin-top: 60px;
  margin-bottom: 20px;
}

#petDetail .detail-header {
  height: 50px;
  margin-bottom: 20px;

  background: -moz-linear-gradient(left,  rgba(255,255,255,0) 0%, rgba(247,247,247,1) 75%);
  background: -webkit-gradient(linear, left top, right top, color-stop(0%,rgba(255,255,255,0)), color-stop(75%,rgba(247,247,247,1)));
  background: -webkit-linear-gradient(left,  rgba(255,255,255,0) 0%,rgba(247,247,247,1) 75%);
  background: -o-linear-gradient(left,  rgba(255,255,255,0) 0%,rgba(247,247,247,1) 75%);
  background: -ms-linear-gradient(left,  rgba(255,255,255,0) 0%,rgba(247,247,247,1) 75%);
  background: linear-gradient(to right,  rgba(255,255,255,0) 0%,rgba(247,247,247,1) 75%);
  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00ffffff', endColorstr='#f7f7f7',GradientType=1 );
}
#petDetail .pet-name {
  position: absolute;
  top: 0;
  left: 0;

  color: #00778b;
  font-size: 42px;
  font-weight: bold;
  line-height: 54px;
}
#petDetail .return-to-ap {
  position: absolute;
  top: 0;
  right: 1.5%;

  color: #00778b;
  font-size: 20px;
  font-weight: bold;
  line-height: 50px;
}

#petDetail .pet-photos {
  position: relative;
}
#petDetail .pet-photos img {
  max-width: 100%;
}

#petDetail .pet-info {
}
#petDetail .pet-info ul {
  padding: 0;
  margin: 0;
  list-style-type: none;
}
#petDetail .pet-info ul li {
  color: #00778b;
  font-size: 18px;
  font-family: 'proximanova-regular';
}
#petDetail .pet-info ul li span {
  font-family: 'proximanova-bold'; /* 'proximanova-semibold' 'proximanova-regular' */
}

#locationFooter {
  background: rgba(247,247,247,1);
}
</style>

<div id="nav-buffer">
</div>

<div id="petDetail" class="std">
  <div class="detail-header row">
    <div class="pet-name">
      Stanley
    </div>

    <div class="return-to-ap">
      Back to results >
    </div>
  </div>

  <div class="row">
    <div class="col col33 pet-photos">
      <img src="https://s3.amazonaws.com/pet-uploads.adoptapet.com/1/2/4/120331392.jpg?336w" />
    </div>
    <div class="col col33 pet-info">
      <ul>
        <li><span>Breed:</span> <?php  ?></li>
        <li><span>Color:</span> White, Black, Red, Golden</li>
        <li><span>Size:</span> Small 25 lbs (11 kg) or less</li>
        <li><span>Sex:</span> Male</li>
      </ul>
    </div>
    <div class="col col33 pet-bio">No bio data</div>
  </div>

  <div class="row"></div>
</div>



<div id="locationFooter">
  <div class="row">Adopt & Shop - Culver City</div>
  <div class="row">
    <div class="col col33">
      <div class="address_phone">
        4235 Sepulveda Blvd.<br/>
        Culver City, CA 90230<br/><br/>
        (310) 93-FOUND (933-6863)<br/><br/>
      </div>
    </div>
    <div class="col col33">
      <div class="hours">
        Store Hours:<br/>
        Monday through Friday:<br/>
        10:00am - 9:00pm<br/><br/>
        Saturday and Sunday:<br/>
        10:00am - 6:00pm<br/><br/>
      </div>
    </div>

    <div class="col col33">
      <div class="services">
        Services Offered:<br/>
        <ul>
          <li>Dog Training</li>
          <li>Dog Daycare</li>
          <li>Dog Grooming</li>
          <li>Pet Microchipping &amp; Registration</li>
          <li>Nail Trimming</li>
          <li>Custom ID Tags</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="row"></div>
</div>



<div class="std">
  <?php
    echo '<ul>';
    echo '<li>'. $currentURL .'</li>';
    echo '<li>'. $id .'</li>';
    echo '<li>'. $key .'</li>';
    echo '<li>'. $url .'</li>';
    echo '<li>'. $showDetail .'</li>';
    echo '</ul>';
  ?>

  <pre>
  <?php print_r($arrayData); ?>
  </pre>
</div>